# Generated by Django 3.2.4 on 2021-09-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_description'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Common',
            new_name='Comment',
        ),
    ]
