# Generated by Django 3.2.4 on 2021-09-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image_url',
            field=models.URLField(),
        ),
    ]
